# Generated by Django 5.1.4 on 2025-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0004_user_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=models.ImageField(blank=True, default='uploads/DProduct.webp', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imgs',
            field=models.ImageField(blank=True, default='uploads/UserProfile/default_profile_picture.jpg', upload_to='uploads/UserProfile/'),
        ),
    ]
